apiVersion: v1
kind: Pod
metadata:
  name: config-env-pod
spec:
  containers:
  - name: my-app
    image: nginx
    command: ["/bin/sh", "-c", "sleep 3600"]
    envFrom:
      - configMapRef:
          name: app-config