apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: U3JpdmlzaGFn        # echo -n "Srivishag" | base64
  DB_PASSWORD: UGFzc1dvcmQxMiMhMw==  # echo -n "PassWord12#!3" | base64