name: Deploy Flask App (Simple)

on:
  push:
    branches: [ "main" ]   # Trigger deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "$EC2_PUBLIC_IP" >> ~/.ssh/known_hosts

      - name: Deploy Flask App
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes \
            "$SSH_USERNAME@$EC2_PUBLIC_IP" << 'EOF'
              # Kill any old Flask process
              pkill -f "python3 app.py" || true

              # Clean previous deployment
              rm -rf ~/flaskapp
              mkdir -p ~/flaskapp
            EOF

          # Copy app files from Task 3
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" ./Task\ 3/ "$SSH_USERNAME@$EC2_PUBLIC_IP:~/flaskapp"

          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes \
            "$SSH_USERNAME@$EC2_PUBLIC_IP" << 'EOF'
              cd ~/flaskapp
              pip3 install --user -r requirements.txt
              nohup python3 app.py > app.log 2>&1 &
            EOF
